# -*- coding: utf-8 -*-
"""Numpy_Assignment_Completed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/davidproton4u/AI-sampleassng/blob/main/Numpy_Assignment_Completed.ipynb

#Numpy Assignments - Create Random Numbers
"""

import numpy as np

mean = (-3, 0)
cov = ([1.0, 0.8], [0.8, 1.0])

np.random.seed(0)
random_number = np.random.multivariate_normal(mean, cov, 500)
print(random_number)
random_number.shape

"""#Numpy Assignment - Visualize with a Scatter Plot"""

import matplotlib.pyplot as plt

mean = (-3, 0)
cov = ([1.0, 0.8], [0.8, 1.0])

np.random.seed(0)

x, y = np.random.multivariate_normal(mean, cov, 500).T

plt.title('The Scatter Plot')
plt.xlabel("X1 Cordinate")
plt.ylabel("X2 Cordinate")
plt.scatter(x, y)
plt.axis('equal')

plt.show()

"""#Numpy Assignment - Visualize with a Histogram"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.xlabel("X1 Cordinate")
plt.ylabel("Frequency")
plt.title("Histogram of X1 Cordinate")

x, y = np.random.multivariate_normal(mean, cov, 500).T
plt.hist(x, color="Pink")
plt.xlim(right=6)
plt.show()

plt.xlabel("X2 Cordinate")
plt.ylabel("Frequency")
plt.title("Histogram of X2 Cordinate")

x, y = np.random.multivariate_normal(mean, cov, 500).T
plt.hist(x, color="Blue")
plt.xlim(left=-5)
plt.show()

"""#Numpy Assignment - Adding Data"""

import matplotlib.pyplot as plt

mean2 = (0, -3)
cov2 = ([1.0, 0.8], [0.8, 1.0])
np.random.seed(0)

x, y = np.random.multivariate_normal(mean, cov, 500).T
x2, y2 = np.random.multivariate_normal(mean2, cov2, 500).T
plt.title('Scatter Plot')
plt.xlabel("x1")
plt.ylabel("x2")
plt.scatter(x, y, alpha=0.5, label="0")
plt.scatter(x2, y2, color="yellow", label="1")
plt.legend(loc='upper right')

plt.show()

"""#Numpy Assignment - Data Combination

"""

random_number1 = np.random.multivariate_normal(mean, cov, 500)
random_number2 = np.random.multivariate_normal(mean2, cov2,500)

np.random.seed(0)

random_numbers_combined = np.concatenate((random_number1, random_number2))

print(random_numbers_combined)
random_numbers_combined.shape

"""#Numpy Assignment - Labeling"""

zeros_ndarray = np.zeros(500)
ones_ndarray = np.ones(500)

first_ndarray=np.insert(random_number1,2,zeros_ndarray,axis=1)
second_ndarray=np.insert(random_number2,2,ones_ndarray,axis=1)
np.random.seed(0)
labeled_ndarray=np.concatenate((first_ndarray, second_ndarray))

print(labeled_ndarray)
labeled_ndarray.shape